### ISSUE TITLE
Non-pdf items don't render or download

### ISSUE THREAD

**Issue by jpvelez** [mycorrhiza-inc/kessler#273]
Occasionally people submit excel files or other documents instead of PDFs.

Here's what happen when you try to load one of them: https://ny.kessler.xyz/files/293731c8-7f3f-45a6-9f19-219ed625064b

**Comment by cappuccinocosmico** [comment]
hmm so a deeper investigation lead to some problems, mainly this document encountered an error during ingest,  when the download link is clicked, it displays a document not found page: https://documents.dps.ny.gov/public/Common/ViewDoc.aspx?DocRefId={10952C93-0000-CE3C-8297-013266E2F0D7} but will actually proceed with the proper download. But our scraper decided to grab the html page instead of the downloaded pdf. However all of these issues still happen with pdfs that were ingested properly, a fix for those should be coming soon: https://ny.kessler.xyz/files/14288f2e-a649-437b-bca5-c96b4dca8cdb

**Comment by cappuccinocosmico** [comment]
Added new issue for the bad puc imports
