### ISSUE TITLE
Show document LLM summaries for all documents

### ISSUE THREAD

**Issue by jpvelez** [mycorrhiza-inc/kessler#299]
Right now none are displaying from what I can tell

**Comment by cappuccinocosmico** [comment]
Current Progress:
![image](https://github.com/user-attachments/assets/02cedb39-078c-4374-92a3-0b933cad0a0b)
Still Left to go:
![image](https://github.com/user-attachments/assets/36390be9-f309-4d26-991a-dc848d9c6b2d)

**Comment by cappuccinocosmico** [comment]
Ok, so it turns out the main reason that document summaries wernt showing up is I deleted the code to render the summaries while refactoring some code, I added them back in, and unprocessed documents give a error message to check back in later for a complete summary. Fixed in #312 
![image](https://github.com/user-attachments/assets/0d02bf70-cf70-452c-aac6-8ed73c082ce4)

**Comment by cappuccinocosmico** [comment]
On second thought, since we are already tracking the document processing pipeline in #291 I am going to go ahead and close this since the main issue was taken care of.
